ALTER TABLE weeks ENABLE ROW LEVEL SECURITY;
ALTER TABLE strength_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE strength_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE strength_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE running_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE athletic_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sport_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE meditation_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sql_learning_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE books_read ENABLE ROW LEVEL SECURITY;
ALTER TABLE writing_pieces ENABLE ROW LEVEL SECURITY;
ALTER TABLE phase_markers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_select" ON weeks FOR SELECT USING (true);
CREATE POLICY "allow_select" ON strength_targets FOR SELECT USING (true);
CREATE POLICY "allow_select" ON strength_sessions FOR SELECT USING (true);
CREATE POLICY "allow_select" ON strength_logs FOR SELECT USING (true);
CREATE POLICY "allow_select" ON running_logs FOR SELECT USING (true);
CREATE POLICY "allow_select" ON athletic_sessions FOR SELECT USING (true);
CREATE POLICY "allow_select" ON sport_sessions FOR SELECT USING (true);
CREATE POLICY "allow_select" ON meditation_sessions FOR SELECT USING (true);
CREATE POLICY "allow_select" ON sql_learning_log FOR SELECT USING (true);
CREATE POLICY "allow_select" ON books_read FOR SELECT USING (true);
CREATE POLICY "allow_select" ON writing_pieces FOR SELECT USING (true);
CREATE POLICY "allow_select" ON phase_markers FOR SELECT USING (true);

CREATE POLICY "allow_insert" ON weeks FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON strength_targets FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON strength_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON strength_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON running_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON athletic_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON sport_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON meditation_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON sql_learning_log FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON books_read FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON writing_pieces FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_insert" ON phase_markers FOR INSERT WITH CHECK (true);

CREATE POLICY "allow_update" ON weeks FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON strength_targets FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON strength_sessions FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON strength_logs FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON running_logs FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON athletic_sessions FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON sport_sessions FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON meditation_sessions FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON sql_learning_log FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON books_read FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON writing_pieces FOR UPDATE USING (true);
CREATE POLICY "allow_update" ON phase_markers FOR UPDATE USING (true);
